name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Value
      description: Why is this important? Who benefits?
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Possible Approach
      description: (Optional) Do you have ideas for implementation?

  - type: textarea
    id: extra
    attributes:
      label: Additional Context
      description: Add references, links, or mockups.
